#!/bin/bash

if [ $# != 2 ]
then
	echo "Usage :\n\n# Rebase current branch with develop branch\n$ rebase-with develop";
	exit;
fi

current=$(git symbolic-ref HEAD | sed -e 's,.*/\(\(.*\)/\(.*\)\),\1,')
if [ ${current:0:5} == "heads" ]
then
	current=$(git symbolic-ref HEAD | sed -e 's,.*/\(\(.*\)/\(.*\)\),\3,')
fi
remote=$1
target=$2
# Check if target branch is exists
exist=$(git show-ref $target)
if [ -z "$exist" ]
then
	echo "Target branch not exists.";
	exit;
fi

git status

echo "Branch : $current  ! Continue?"
read -p  Devam

stashed=false
files=$(git diff-index --name-only --cached HEAD)
if [ "$files" != "" ]
then
    stashed=true
    git stash
fi

git fetch $remote && git checkout $target && git merge $remote/$target && git checkout $current && git rebase $target

if "$stashed" == true
then
    git stash pop
fi